version: '3'
services:
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - ./tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
  
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - ./unifi/Unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      # - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./sonarr:/config
      - ${TV}:/tv
      - ${DOWNLOADS}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped


  radarr1:      
    image: ghcr.io/linuxserver/radarr
    container_name: radarr1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./radarr:/config
      - ${MEDIA}:/movies
      - ${DOWNLOADS}:/data
    ports:
      - 7877:7878
    restart: unless-stopped


  radarr4k:      
    image: ghcr.io/linuxserver/radarr
    container_name: radarr4k
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./radarr4k:/config
      - ${MEDIA}:/movies
      - ${DOWNLOADS}:/data
    ports:
      - 7876:7878
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./syncthing:/config
      -  ${BACKUPS}/syncthing:/data1
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    ports:
        - 8001:80
    volumes:
        - ./organizr:/config
    environment:
        - PUID=1001
        - PGID=1001
        - TZ=Europe/London

  thelounge:
    container_name: thelounge
    ports:
        - '9099:9000'
    volumes:
        - './thelounge:/var/opt/thelounge'
    restart: always
    image: 'thelounge/thelounge:latest'



  audiobookshelf:
    ports:
      - '13378:80'
    volumes:
      - './abs/abs_data:/config'
      - './abs/metadata:/metadata'
      - '${MEDIA}Audiobooks/:/audiobooks'
      - '${MEDIA}Podcasts/:/podcasts'
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf
    restart: unless-stopped

  
  vpn:
    image: thrnz/docker-wireguard-pia
    volumes:
      - ./pia_vpn/:/pia
    cap_add:
      - NET_ADMIN
      # SYS_MODULE might not be needed with a 5.6+ kernel?
      - SYS_MODULE
    environment:
      # The following env vars are required:
      - LOC=swiss
      - USER=${PIA_USER}
      - PASS=${PIA_PASS}
      # The rest are optional:
      - LOCAL_NETWORK=10.0.0.0/8, 192.168.0.0/16
      #- KEEPALIVE=25
      - VPNDNS=8.8.8.8,8.8.4.4
      - PORT_FORWARDING=1
      #- WG_USERSPACE=1
      - PORT_PERSIST=1
    
    ports:
      - 8182:8182
      - 9696:9696
      - 9117:9117
    sysctls:
      # wg-quick fails to set this without --privileged, so set it here instead if needed
      - net.ipv4.conf.all.src_valid_mark=1
      # May as well disable ipv6. Should be blocked anyway.
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrentvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8182
    volumes:
      - ./qbitconf:/config
      - ${DOWNLOADS}:/downloads
    restart: unless-stopped
    network_mode: service:vpn

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./prowlarr:/config
    network_mode: service:vpn
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
    volumes:
      - ./jackett:/config
    network_mode: service:vpn
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./readerr:/config
      - ${MEDIA}/Audiobooks:/books #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

